// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recipe = {
  id: number | null;
  name: string;
  category: string;
  ingredients: Array<string>;
  steps: Array<string>;
  images: Array<string>;
  notes: string | null;
};
